name: concepts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=23.3.*
  - cudatoolkit=11.2.*
  - cudnn=8.1.*
  - numpy=1.23.5
  - pandas=1.5.*
  - scipy=1.10.*
  - scikit-learn=1.2.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - pillow=9.5.*
  - h5py=3.8.*
  - joblib=1.2.*
  - tqdm
  - ipykernel
  - notebook
  - jupyterlab
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu117
      - tensorflow==2.10.1
      - keras==2.10.0
      - protobuf==3.19.6
      - tcav==0.2.2
      - zss==1.2.0
      - gdown==4.6.0
      - gensim==4.2.0
      - nltk==3.8.1
      - filelock==3.8.2
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - torchaudio==0.13.1+cu117
      - pytorch-lightning==1.5.8
      - torchmetrics==0.11.4
      - scikit-learn-extra==0.2.0
      - wandb==0.13.9
      - -e .
      - -e ./cem
